  sudo: required
  dist: trusty
languanges: php

php:
  - 7.1.9

brances:
  only:
    - master #-> Staging Server
    - develop #-> DevServer

#Sebelum melakukan atau eksekusi script
#Install kebutuhan os. ext: mod-php dll.
before_install:
  - curl -LO
  - chmod +x ./irgi
  - sudo mv ./irgi/tugaspaw
  - irgi

#Pre Exekution
#testing dll.
before_script:

#Main Execution
script:
